// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoservice

import (
	"context"

	"github.com/jkaveri/goservice"
	mock "github.com/stretchr/testify/mock"
)

// NewCronJobService creates a new instance of CronJobService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCronJobService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CronJobService {
	mock := &CronJobService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CronJobService is an autogenerated mock type for the CronJobService type
type CronJobService struct {
	mock.Mock
}

type CronJobService_Expecter struct {
	mock *mock.Mock
}

func (_m *CronJobService) EXPECT() *CronJobService_Expecter {
	return &CronJobService_Expecter{mock: &_m.Mock}
}

// RegisterJobs provides a mock function for the type CronJobService
func (_mock *CronJobService) RegisterJobs(ctx context.Context, service goservice.Service) {
	_mock.Called(ctx, service)
	return
}

// CronJobService_RegisterJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterJobs'
type CronJobService_RegisterJobs_Call struct {
	*mock.Call
}

// RegisterJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - service goservice.Service
func (_e *CronJobService_Expecter) RegisterJobs(ctx interface{}, service interface{}) *CronJobService_RegisterJobs_Call {
	return &CronJobService_RegisterJobs_Call{Call: _e.mock.On("RegisterJobs", ctx, service)}
}

func (_c *CronJobService_RegisterJobs_Call) Run(run func(ctx context.Context, service goservice.Service)) *CronJobService_RegisterJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 goservice.Service
		if args[1] != nil {
			arg1 = args[1].(goservice.Service)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CronJobService_RegisterJobs_Call) Return() *CronJobService_RegisterJobs_Call {
	_c.Call.Return()
	return _c
}

func (_c *CronJobService_RegisterJobs_Call) RunAndReturn(run func(ctx context.Context, service goservice.Service)) *CronJobService_RegisterJobs_Call {
	_c.Run(run)
	return _c
}
