// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoservice

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewGRPCService creates a new instance of GRPCService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGRPCService(t interface {
	mock.TestingT
	Cleanup(func())
}) *GRPCService {
	mock := &GRPCService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GRPCService is an autogenerated mock type for the GRPCService type
type GRPCService struct {
	mock.Mock
}

type GRPCService_Expecter struct {
	mock *mock.Mock
}

func (_m *GRPCService) EXPECT() *GRPCService_Expecter {
	return &GRPCService_Expecter{mock: &_m.Mock}
}

// GRPCServerOptions provides a mock function for the type GRPCService
func (_mock *GRPCService) GRPCServerOptions() []grpc.ServerOption {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GRPCServerOptions")
	}

	var r0 []grpc.ServerOption
	if returnFunc, ok := ret.Get(0).(func() []grpc.ServerOption); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]grpc.ServerOption)
		}
	}
	return r0
}

// GRPCService_GRPCServerOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GRPCServerOptions'
type GRPCService_GRPCServerOptions_Call struct {
	*mock.Call
}

// GRPCServerOptions is a helper method to define mock.On call
func (_e *GRPCService_Expecter) GRPCServerOptions() *GRPCService_GRPCServerOptions_Call {
	return &GRPCService_GRPCServerOptions_Call{Call: _e.mock.On("GRPCServerOptions")}
}

func (_c *GRPCService_GRPCServerOptions_Call) Run(run func()) *GRPCService_GRPCServerOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GRPCService_GRPCServerOptions_Call) Return(serverOptions []grpc.ServerOption) *GRPCService_GRPCServerOptions_Call {
	_c.Call.Return(serverOptions)
	return _c
}

func (_c *GRPCService_GRPCServerOptions_Call) RunAndReturn(run func() []grpc.ServerOption) *GRPCService_GRPCServerOptions_Call {
	_c.Call.Return(run)
	return _c
}

// GRPCUnaryInterceptors provides a mock function for the type GRPCService
func (_mock *GRPCService) GRPCUnaryInterceptors() []grpc.UnaryServerInterceptor {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GRPCUnaryInterceptors")
	}

	var r0 []grpc.UnaryServerInterceptor
	if returnFunc, ok := ret.Get(0).(func() []grpc.UnaryServerInterceptor); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]grpc.UnaryServerInterceptor)
		}
	}
	return r0
}

// GRPCService_GRPCUnaryInterceptors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GRPCUnaryInterceptors'
type GRPCService_GRPCUnaryInterceptors_Call struct {
	*mock.Call
}

// GRPCUnaryInterceptors is a helper method to define mock.On call
func (_e *GRPCService_Expecter) GRPCUnaryInterceptors() *GRPCService_GRPCUnaryInterceptors_Call {
	return &GRPCService_GRPCUnaryInterceptors_Call{Call: _e.mock.On("GRPCUnaryInterceptors")}
}

func (_c *GRPCService_GRPCUnaryInterceptors_Call) Run(run func()) *GRPCService_GRPCUnaryInterceptors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GRPCService_GRPCUnaryInterceptors_Call) Return(unaryServerInterceptors []grpc.UnaryServerInterceptor) *GRPCService_GRPCUnaryInterceptors_Call {
	_c.Call.Return(unaryServerInterceptors)
	return _c
}

func (_c *GRPCService_GRPCUnaryInterceptors_Call) RunAndReturn(run func() []grpc.UnaryServerInterceptor) *GRPCService_GRPCUnaryInterceptors_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterGRPC provides a mock function for the type GRPCService
func (_mock *GRPCService) RegisterGRPC(ctx context.Context, s *grpc.Server) {
	_mock.Called(ctx, s)
	return
}

// GRPCService_RegisterGRPC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterGRPC'
type GRPCService_RegisterGRPC_Call struct {
	*mock.Call
}

// RegisterGRPC is a helper method to define mock.On call
//   - ctx context.Context
//   - s *grpc.Server
func (_e *GRPCService_Expecter) RegisterGRPC(ctx interface{}, s interface{}) *GRPCService_RegisterGRPC_Call {
	return &GRPCService_RegisterGRPC_Call{Call: _e.mock.On("RegisterGRPC", ctx, s)}
}

func (_c *GRPCService_RegisterGRPC_Call) Run(run func(ctx context.Context, s *grpc.Server)) *GRPCService_RegisterGRPC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *grpc.Server
		if args[1] != nil {
			arg1 = args[1].(*grpc.Server)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GRPCService_RegisterGRPC_Call) Return() *GRPCService_RegisterGRPC_Call {
	_c.Call.Return()
	return _c
}

func (_c *GRPCService_RegisterGRPC_Call) RunAndReturn(run func(ctx context.Context, s *grpc.Server)) *GRPCService_RegisterGRPC_Call {
	_c.Run(run)
	return _c
}
