// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoservice

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewHTTPService creates a new instance of HTTPService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPService {
	mock := &HTTPService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HTTPService is an autogenerated mock type for the HTTPService type
type HTTPService struct {
	mock.Mock
}

type HTTPService_Expecter struct {
	mock *mock.Mock
}

func (_m *HTTPService) EXPECT() *HTTPService_Expecter {
	return &HTTPService_Expecter{mock: &_m.Mock}
}

// RegisterHTTP provides a mock function for the type HTTPService
func (_mock *HTTPService) RegisterHTTP(ctx context.Context, s *http.Server) http.Handler {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for RegisterHTTP")
	}

	var r0 http.Handler
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Server) http.Handler); ok {
		r0 = returnFunc(ctx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}
	return r0
}

// HTTPService_RegisterHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHTTP'
type HTTPService_RegisterHTTP_Call struct {
	*mock.Call
}

// RegisterHTTP is a helper method to define mock.On call
//   - ctx context.Context
//   - s *http.Server
func (_e *HTTPService_Expecter) RegisterHTTP(ctx interface{}, s interface{}) *HTTPService_RegisterHTTP_Call {
	return &HTTPService_RegisterHTTP_Call{Call: _e.mock.On("RegisterHTTP", ctx, s)}
}

func (_c *HTTPService_RegisterHTTP_Call) Run(run func(ctx context.Context, s *http.Server)) *HTTPService_RegisterHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *http.Server
		if args[1] != nil {
			arg1 = args[1].(*http.Server)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HTTPService_RegisterHTTP_Call) Return(handler http.Handler) *HTTPService_RegisterHTTP_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *HTTPService_RegisterHTTP_Call) RunAndReturn(run func(ctx context.Context, s *http.Server) http.Handler) *HTTPService_RegisterHTTP_Call {
	_c.Call.Return(run)
	return _c
}
