// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoservice

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewOnStartListener creates a new instance of OnStartListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOnStartListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *OnStartListener {
	mock := &OnStartListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OnStartListener is an autogenerated mock type for the OnStartListener type
type OnStartListener struct {
	mock.Mock
}

type OnStartListener_Expecter struct {
	mock *mock.Mock
}

func (_m *OnStartListener) EXPECT() *OnStartListener_Expecter {
	return &OnStartListener_Expecter{mock: &_m.Mock}
}

// OnStart provides a mock function for the type OnStartListener
func (_mock *OnStartListener) OnStart(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for OnStart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OnStartListener_OnStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnStart'
type OnStartListener_OnStart_Call struct {
	*mock.Call
}

// OnStart is a helper method to define mock.On call
//   - context1 context.Context
func (_e *OnStartListener_Expecter) OnStart(context1 interface{}) *OnStartListener_OnStart_Call {
	return &OnStartListener_OnStart_Call{Call: _e.mock.On("OnStart", context1)}
}

func (_c *OnStartListener_OnStart_Call) Run(run func(context1 context.Context)) *OnStartListener_OnStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OnStartListener_OnStart_Call) Return(err error) *OnStartListener_OnStart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OnStartListener_OnStart_Call) RunAndReturn(run func(context1 context.Context) error) *OnStartListener_OnStart_Call {
	_c.Call.Return(run)
	return _c
}
