// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgoservice

import (
	mock "github.com/stretchr/testify/mock"
)

// NewOnStopListener creates a new instance of OnStopListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOnStopListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *OnStopListener {
	mock := &OnStopListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OnStopListener is an autogenerated mock type for the OnStopListener type
type OnStopListener struct {
	mock.Mock
}

type OnStopListener_Expecter struct {
	mock *mock.Mock
}

func (_m *OnStopListener) EXPECT() *OnStopListener_Expecter {
	return &OnStopListener_Expecter{mock: &_m.Mock}
}

// OnStop provides a mock function for the type OnStopListener
func (_mock *OnStopListener) OnStop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OnStop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OnStopListener_OnStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnStop'
type OnStopListener_OnStop_Call struct {
	*mock.Call
}

// OnStop is a helper method to define mock.On call
func (_e *OnStopListener_Expecter) OnStop() *OnStopListener_OnStop_Call {
	return &OnStopListener_OnStop_Call{Call: _e.mock.On("OnStop")}
}

func (_c *OnStopListener_OnStop_Call) Run(run func()) *OnStopListener_OnStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OnStopListener_OnStop_Call) Return(err error) *OnStopListener_OnStop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OnStopListener_OnStop_Call) RunAndReturn(run func() error) *OnStopListener_OnStop_Call {
	_c.Call.Return(run)
	return _c
}
