// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockerrors

import (
	mock "github.com/stretchr/testify/mock"
)

// NewCodeError creates a new instance of CodeError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCodeError(t interface {
	mock.TestingT
	Cleanup(func())
}) *CodeError {
	mock := &CodeError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CodeError is an autogenerated mock type for the CodeError type
type CodeError struct {
	mock.Mock
}

type CodeError_Expecter struct {
	mock *mock.Mock
}

func (_m *CodeError) EXPECT() *CodeError_Expecter {
	return &CodeError_Expecter{mock: &_m.Mock}
}

// Code provides a mock function for the type CodeError
func (_mock *CodeError) Code() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Code")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CodeError_Code_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Code'
type CodeError_Code_Call struct {
	*mock.Call
}

// Code is a helper method to define mock.On call
func (_e *CodeError_Expecter) Code() *CodeError_Code_Call {
	return &CodeError_Code_Call{Call: _e.mock.On("Code")}
}

func (_c *CodeError_Code_Call) Run(run func()) *CodeError_Code_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CodeError_Code_Call) Return(s string) *CodeError_Code_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CodeError_Code_Call) RunAndReturn(run func() string) *CodeError_Code_Call {
	_c.Call.Return(run)
	return _c
}
