// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockerrors

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMetadataError creates a new instance of MetadataError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetadataError(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetadataError {
	mock := &MetadataError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MetadataError is an autogenerated mock type for the MetadataError type
type MetadataError struct {
	mock.Mock
}

type MetadataError_Expecter struct {
	mock *mock.Mock
}

func (_m *MetadataError) EXPECT() *MetadataError_Expecter {
	return &MetadataError_Expecter{mock: &_m.Mock}
}

// Metadata provides a mock function for the type MetadataError
func (_mock *MetadataError) Metadata() map[string]interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 map[string]interface{}
	if returnFunc, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}
	return r0
}

// MetadataError_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MetadataError_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MetadataError_Expecter) Metadata() *MetadataError_Metadata_Call {
	return &MetadataError_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MetadataError_Metadata_Call) Run(run func()) *MetadataError_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MetadataError_Metadata_Call) Return(stringToIfaceVal map[string]interface{}) *MetadataError_Metadata_Call {
	_c.Call.Return(stringToIfaceVal)
	return _c
}

func (_c *MetadataError_Metadata_Call) RunAndReturn(run func() map[string]interface{}) *MetadataError_Metadata_Call {
	_c.Call.Return(run)
	return _c
}
