// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockerrors

import (
	"github.com/jkaveri/goservice/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewStackError creates a new instance of StackError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStackError(t interface {
	mock.TestingT
	Cleanup(func())
}) *StackError {
	mock := &StackError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StackError is an autogenerated mock type for the StackError type
type StackError struct {
	mock.Mock
}

type StackError_Expecter struct {
	mock *mock.Mock
}

func (_m *StackError) EXPECT() *StackError_Expecter {
	return &StackError_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type StackError
func (_mock *StackError) Error() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// StackError_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type StackError_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *StackError_Expecter) Error() *StackError_Error_Call {
	return &StackError_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *StackError_Error_Call) Run(run func()) *StackError_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StackError_Error_Call) Return(s string) *StackError_Error_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *StackError_Error_Call) RunAndReturn(run func() string) *StackError_Error_Call {
	_c.Call.Return(run)
	return _c
}

// StackTrace provides a mock function for the type StackError
func (_mock *StackError) StackTrace() errors.StackTrace {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StackTrace")
	}

	var r0 errors.StackTrace
	if returnFunc, ok := ret.Get(0).(func() errors.StackTrace); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.StackTrace)
		}
	}
	return r0
}

// StackError_StackTrace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StackTrace'
type StackError_StackTrace_Call struct {
	*mock.Call
}

// StackTrace is a helper method to define mock.On call
func (_e *StackError_Expecter) StackTrace() *StackError_StackTrace_Call {
	return &StackError_StackTrace_Call{Call: _e.mock.On("StackTrace")}
}

func (_c *StackError_StackTrace_Call) Run(run func()) *StackError_StackTrace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StackError_StackTrace_Call) Return(stackTrace errors.StackTrace) *StackError_StackTrace_Call {
	_c.Call.Return(stackTrace)
	return _c
}

func (_c *StackError_StackTrace_Call) RunAndReturn(run func() errors.StackTrace) *StackError_StackTrace_Call {
	_c.Call.Return(run)
	return _c
}
