// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockerrors

import (
	mock "github.com/stretchr/testify/mock"
)

// NewUserMessageError creates a new instance of UserMessageError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserMessageError(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserMessageError {
	mock := &UserMessageError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserMessageError is an autogenerated mock type for the UserMessageError type
type UserMessageError struct {
	mock.Mock
}

type UserMessageError_Expecter struct {
	mock *mock.Mock
}

func (_m *UserMessageError) EXPECT() *UserMessageError_Expecter {
	return &UserMessageError_Expecter{mock: &_m.Mock}
}

// UserMessage provides a mock function for the type UserMessageError
func (_mock *UserMessageError) UserMessage() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserMessage")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// UserMessageError_UserMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserMessage'
type UserMessageError_UserMessage_Call struct {
	*mock.Call
}

// UserMessage is a helper method to define mock.On call
func (_e *UserMessageError_Expecter) UserMessage() *UserMessageError_UserMessage_Call {
	return &UserMessageError_UserMessage_Call{Call: _e.mock.On("UserMessage")}
}

func (_c *UserMessageError_UserMessage_Call) Run(run func()) *UserMessageError_UserMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UserMessageError_UserMessage_Call) Return(s string) *UserMessageError_UserMessage_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *UserMessageError_UserMessage_Call) RunAndReturn(run func() string) *UserMessageError_UserMessage_Call {
	_c.Call.Return(run)
	return _c
}
