// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package goservice

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockOnStopListener creates a new instance of MockOnStopListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnStopListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnStopListener {
	mock := &MockOnStopListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOnStopListener is an autogenerated mock type for the OnStopListener type
type MockOnStopListener struct {
	mock.Mock
}

type MockOnStopListener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnStopListener) EXPECT() *MockOnStopListener_Expecter {
	return &MockOnStopListener_Expecter{mock: &_m.Mock}
}

// OnStop provides a mock function for the type MockOnStopListener
func (_mock *MockOnStopListener) OnStop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OnStop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOnStopListener_OnStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnStop'
type MockOnStopListener_OnStop_Call struct {
	*mock.Call
}

// OnStop is a helper method to define mock.On call
func (_e *MockOnStopListener_Expecter) OnStop() *MockOnStopListener_OnStop_Call {
	return &MockOnStopListener_OnStop_Call{Call: _e.mock.On("OnStop")}
}

func (_c *MockOnStopListener_OnStop_Call) Run(run func()) *MockOnStopListener_OnStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnStopListener_OnStop_Call) Return(err error) *MockOnStopListener_OnStop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOnStopListener_OnStop_Call) RunAndReturn(run func() error) *MockOnStopListener_OnStop_Call {
	_c.Call.Return(run)
	return _c
}
