// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package goservice

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockServerCustomizer creates a new instance of MockServerCustomizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerCustomizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerCustomizer {
	mock := &MockServerCustomizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerCustomizer is an autogenerated mock type for the ServerCustomizer type
type MockServerCustomizer struct {
	mock.Mock
}

type MockServerCustomizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerCustomizer) EXPECT() *MockServerCustomizer_Expecter {
	return &MockServerCustomizer_Expecter{mock: &_m.Mock}
}

// SetupHTTPServer provides a mock function for the type MockServerCustomizer
func (_mock *MockServerCustomizer) SetupHTTPServer(server *http.Server) {
	_mock.Called(server)
	return
}

// MockServerCustomizer_SetupHTTPServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupHTTPServer'
type MockServerCustomizer_SetupHTTPServer_Call struct {
	*mock.Call
}

// SetupHTTPServer is a helper method to define mock.On call
//   - server *http.Server
func (_e *MockServerCustomizer_Expecter) SetupHTTPServer(server interface{}) *MockServerCustomizer_SetupHTTPServer_Call {
	return &MockServerCustomizer_SetupHTTPServer_Call{Call: _e.mock.On("SetupHTTPServer", server)}
}

func (_c *MockServerCustomizer_SetupHTTPServer_Call) Run(run func(server *http.Server)) *MockServerCustomizer_SetupHTTPServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Server
		if args[0] != nil {
			arg0 = args[0].(*http.Server)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerCustomizer_SetupHTTPServer_Call) Return() *MockServerCustomizer_SetupHTTPServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerCustomizer_SetupHTTPServer_Call) RunAndReturn(run func(server *http.Server)) *MockServerCustomizer_SetupHTTPServer_Call {
	_c.Run(run)
	return _c
}
