// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package goservice

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHTTPService creates a new instance of MockHTTPService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPService {
	mock := &MockHTTPService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHTTPService is an autogenerated mock type for the HTTPService type
type MockHTTPService struct {
	mock.Mock
}

type MockHTTPService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPService) EXPECT() *MockHTTPService_Expecter {
	return &MockHTTPService_Expecter{mock: &_m.Mock}
}

// RegisterHTTP provides a mock function for the type MockHTTPService
func (_mock *MockHTTPService) RegisterHTTP(ctx context.Context, s *http.Server) http.Handler {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for RegisterHTTP")
	}

	var r0 http.Handler
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Server) http.Handler); ok {
		r0 = returnFunc(ctx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}
	return r0
}

// MockHTTPService_RegisterHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHTTP'
type MockHTTPService_RegisterHTTP_Call struct {
	*mock.Call
}

// RegisterHTTP is a helper method to define mock.On call
//   - ctx context.Context
//   - s *http.Server
func (_e *MockHTTPService_Expecter) RegisterHTTP(ctx interface{}, s interface{}) *MockHTTPService_RegisterHTTP_Call {
	return &MockHTTPService_RegisterHTTP_Call{Call: _e.mock.On("RegisterHTTP", ctx, s)}
}

func (_c *MockHTTPService_RegisterHTTP_Call) Run(run func(ctx context.Context, s *http.Server)) *MockHTTPService_RegisterHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *http.Server
		if args[1] != nil {
			arg1 = args[1].(*http.Server)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHTTPService_RegisterHTTP_Call) Return(handler http.Handler) *MockHTTPService_RegisterHTTP_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *MockHTTPService_RegisterHTTP_Call) RunAndReturn(run func(ctx context.Context, s *http.Server) http.Handler) *MockHTTPService_RegisterHTTP_Call {
	_c.Call.Return(run)
	return _c
}
