// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package goservice

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockGRPCService creates a new instance of MockGRPCService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGRPCService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGRPCService {
	mock := &MockGRPCService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGRPCService is an autogenerated mock type for the GRPCService type
type MockGRPCService struct {
	mock.Mock
}

type MockGRPCService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGRPCService) EXPECT() *MockGRPCService_Expecter {
	return &MockGRPCService_Expecter{mock: &_m.Mock}
}

// GRPCServerOptions provides a mock function for the type MockGRPCService
func (_mock *MockGRPCService) GRPCServerOptions() []grpc.ServerOption {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GRPCServerOptions")
	}

	var r0 []grpc.ServerOption
	if returnFunc, ok := ret.Get(0).(func() []grpc.ServerOption); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]grpc.ServerOption)
		}
	}
	return r0
}

// MockGRPCService_GRPCServerOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GRPCServerOptions'
type MockGRPCService_GRPCServerOptions_Call struct {
	*mock.Call
}

// GRPCServerOptions is a helper method to define mock.On call
func (_e *MockGRPCService_Expecter) GRPCServerOptions() *MockGRPCService_GRPCServerOptions_Call {
	return &MockGRPCService_GRPCServerOptions_Call{Call: _e.mock.On("GRPCServerOptions")}
}

func (_c *MockGRPCService_GRPCServerOptions_Call) Run(run func()) *MockGRPCService_GRPCServerOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGRPCService_GRPCServerOptions_Call) Return(serverOptions []grpc.ServerOption) *MockGRPCService_GRPCServerOptions_Call {
	_c.Call.Return(serverOptions)
	return _c
}

func (_c *MockGRPCService_GRPCServerOptions_Call) RunAndReturn(run func() []grpc.ServerOption) *MockGRPCService_GRPCServerOptions_Call {
	_c.Call.Return(run)
	return _c
}

// GRPCUnaryInterceptors provides a mock function for the type MockGRPCService
func (_mock *MockGRPCService) GRPCUnaryInterceptors() []grpc.UnaryServerInterceptor {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GRPCUnaryInterceptors")
	}

	var r0 []grpc.UnaryServerInterceptor
	if returnFunc, ok := ret.Get(0).(func() []grpc.UnaryServerInterceptor); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]grpc.UnaryServerInterceptor)
		}
	}
	return r0
}

// MockGRPCService_GRPCUnaryInterceptors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GRPCUnaryInterceptors'
type MockGRPCService_GRPCUnaryInterceptors_Call struct {
	*mock.Call
}

// GRPCUnaryInterceptors is a helper method to define mock.On call
func (_e *MockGRPCService_Expecter) GRPCUnaryInterceptors() *MockGRPCService_GRPCUnaryInterceptors_Call {
	return &MockGRPCService_GRPCUnaryInterceptors_Call{Call: _e.mock.On("GRPCUnaryInterceptors")}
}

func (_c *MockGRPCService_GRPCUnaryInterceptors_Call) Run(run func()) *MockGRPCService_GRPCUnaryInterceptors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGRPCService_GRPCUnaryInterceptors_Call) Return(unaryServerInterceptors []grpc.UnaryServerInterceptor) *MockGRPCService_GRPCUnaryInterceptors_Call {
	_c.Call.Return(unaryServerInterceptors)
	return _c
}

func (_c *MockGRPCService_GRPCUnaryInterceptors_Call) RunAndReturn(run func() []grpc.UnaryServerInterceptor) *MockGRPCService_GRPCUnaryInterceptors_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterGRPC provides a mock function for the type MockGRPCService
func (_mock *MockGRPCService) RegisterGRPC(ctx context.Context, s *grpc.Server) {
	_mock.Called(ctx, s)
	return
}

// MockGRPCService_RegisterGRPC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterGRPC'
type MockGRPCService_RegisterGRPC_Call struct {
	*mock.Call
}

// RegisterGRPC is a helper method to define mock.On call
//   - ctx context.Context
//   - s *grpc.Server
func (_e *MockGRPCService_Expecter) RegisterGRPC(ctx interface{}, s interface{}) *MockGRPCService_RegisterGRPC_Call {
	return &MockGRPCService_RegisterGRPC_Call{Call: _e.mock.On("RegisterGRPC", ctx, s)}
}

func (_c *MockGRPCService_RegisterGRPC_Call) Run(run func(ctx context.Context, s *grpc.Server)) *MockGRPCService_RegisterGRPC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *grpc.Server
		if args[1] != nil {
			arg1 = args[1].(*grpc.Server)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGRPCService_RegisterGRPC_Call) Return() *MockGRPCService_RegisterGRPC_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGRPCService_RegisterGRPC_Call) RunAndReturn(run func(ctx context.Context, s *grpc.Server)) *MockGRPCService_RegisterGRPC_Call {
	_c.Run(run)
	return _c
}
