// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package goservice

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCronJobService creates a new instance of MockCronJobService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCronJobService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCronJobService {
	mock := &MockCronJobService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCronJobService is an autogenerated mock type for the CronJobService type
type MockCronJobService struct {
	mock.Mock
}

type MockCronJobService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCronJobService) EXPECT() *MockCronJobService_Expecter {
	return &MockCronJobService_Expecter{mock: &_m.Mock}
}

// RegisterJobs provides a mock function for the type MockCronJobService
func (_mock *MockCronJobService) RegisterJobs(ctx context.Context, service Service) {
	_mock.Called(ctx, service)
	return
}

// MockCronJobService_RegisterJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterJobs'
type MockCronJobService_RegisterJobs_Call struct {
	*mock.Call
}

// RegisterJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - service Service
func (_e *MockCronJobService_Expecter) RegisterJobs(ctx interface{}, service interface{}) *MockCronJobService_RegisterJobs_Call {
	return &MockCronJobService_RegisterJobs_Call{Call: _e.mock.On("RegisterJobs", ctx, service)}
}

func (_c *MockCronJobService_RegisterJobs_Call) Run(run func(ctx context.Context, service Service)) *MockCronJobService_RegisterJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Service
		if args[1] != nil {
			arg1 = args[1].(Service)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCronJobService_RegisterJobs_Call) Return() *MockCronJobService_RegisterJobs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCronJobService_RegisterJobs_Call) RunAndReturn(run func(ctx context.Context, service Service)) *MockCronJobService_RegisterJobs_Call {
	_c.Run(run)
	return _c
}
