// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package validate

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAllErrorsLister creates a new instance of MockAllErrorsLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAllErrorsLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAllErrorsLister {
	mock := &MockAllErrorsLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAllErrorsLister is an autogenerated mock type for the AllErrorsLister type
type MockAllErrorsLister struct {
	mock.Mock
}

type MockAllErrorsLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAllErrorsLister) EXPECT() *MockAllErrorsLister_Expecter {
	return &MockAllErrorsLister_Expecter{mock: &_m.Mock}
}

// AllErrors provides a mock function for the type MockAllErrorsLister
func (_mock *MockAllErrorsLister) AllErrors() []error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllErrors")
	}

	var r0 []error
	if returnFunc, ok := ret.Get(0).(func() []error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}
	return r0
}

// MockAllErrorsLister_AllErrors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllErrors'
type MockAllErrorsLister_AllErrors_Call struct {
	*mock.Call
}

// AllErrors is a helper method to define mock.On call
func (_e *MockAllErrorsLister_Expecter) AllErrors() *MockAllErrorsLister_AllErrors_Call {
	return &MockAllErrorsLister_AllErrors_Call{Call: _e.mock.On("AllErrors")}
}

func (_c *MockAllErrorsLister_AllErrors_Call) Run(run func()) *MockAllErrorsLister_AllErrors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAllErrorsLister_AllErrors_Call) Return(errs []error) *MockAllErrorsLister_AllErrors_Call {
	_c.Call.Return(errs)
	return _c
}

func (_c *MockAllErrorsLister_AllErrors_Call) RunAndReturn(run func() []error) *MockAllErrorsLister_AllErrors_Call {
	_c.Call.Return(run)
	return _c
}
