// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package validate

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFieldReason creates a new instance of MockFieldReason. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFieldReason(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFieldReason {
	mock := &MockFieldReason{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFieldReason is an autogenerated mock type for the FieldReason type
type MockFieldReason struct {
	mock.Mock
}

type MockFieldReason_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFieldReason) EXPECT() *MockFieldReason_Expecter {
	return &MockFieldReason_Expecter{mock: &_m.Mock}
}

// Field provides a mock function for the type MockFieldReason
func (_mock *MockFieldReason) Field() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Field")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFieldReason_Field_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Field'
type MockFieldReason_Field_Call struct {
	*mock.Call
}

// Field is a helper method to define mock.On call
func (_e *MockFieldReason_Expecter) Field() *MockFieldReason_Field_Call {
	return &MockFieldReason_Field_Call{Call: _e.mock.On("Field")}
}

func (_c *MockFieldReason_Field_Call) Run(run func()) *MockFieldReason_Field_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFieldReason_Field_Call) Return(s string) *MockFieldReason_Field_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFieldReason_Field_Call) RunAndReturn(run func() string) *MockFieldReason_Field_Call {
	_c.Call.Return(run)
	return _c
}

// Reason provides a mock function for the type MockFieldReason
func (_mock *MockFieldReason) Reason() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reason")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFieldReason_Reason_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reason'
type MockFieldReason_Reason_Call struct {
	*mock.Call
}

// Reason is a helper method to define mock.On call
func (_e *MockFieldReason_Expecter) Reason() *MockFieldReason_Reason_Call {
	return &MockFieldReason_Reason_Call{Call: _e.mock.On("Reason")}
}

func (_c *MockFieldReason_Reason_Call) Run(run func()) *MockFieldReason_Reason_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFieldReason_Reason_Call) Return(s string) *MockFieldReason_Reason_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFieldReason_Reason_Call) RunAndReturn(run func() string) *MockFieldReason_Reason_Call {
	_c.Call.Return(run)
	return _c
}
