// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockvalidate

import (
	mock "github.com/stretchr/testify/mock"
)

// NewFieldReason creates a new instance of FieldReason. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFieldReason(t interface {
	mock.TestingT
	Cleanup(func())
}) *FieldReason {
	mock := &FieldReason{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FieldReason is an autogenerated mock type for the FieldReason type
type FieldReason struct {
	mock.Mock
}

type FieldReason_Expecter struct {
	mock *mock.Mock
}

func (_m *FieldReason) EXPECT() *FieldReason_Expecter {
	return &FieldReason_Expecter{mock: &_m.Mock}
}

// Field provides a mock function for the type FieldReason
func (_mock *FieldReason) Field() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Field")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// FieldReason_Field_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Field'
type FieldReason_Field_Call struct {
	*mock.Call
}

// Field is a helper method to define mock.On call
func (_e *FieldReason_Expecter) Field() *FieldReason_Field_Call {
	return &FieldReason_Field_Call{Call: _e.mock.On("Field")}
}

func (_c *FieldReason_Field_Call) Run(run func()) *FieldReason_Field_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FieldReason_Field_Call) Return(s string) *FieldReason_Field_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *FieldReason_Field_Call) RunAndReturn(run func() string) *FieldReason_Field_Call {
	_c.Call.Return(run)
	return _c
}

// Reason provides a mock function for the type FieldReason
func (_mock *FieldReason) Reason() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reason")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// FieldReason_Reason_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reason'
type FieldReason_Reason_Call struct {
	*mock.Call
}

// Reason is a helper method to define mock.On call
func (_e *FieldReason_Expecter) Reason() *FieldReason_Reason_Call {
	return &FieldReason_Reason_Call{Call: _e.mock.On("Reason")}
}

func (_c *FieldReason_Reason_Call) Run(run func()) *FieldReason_Reason_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FieldReason_Reason_Call) Return(s string) *FieldReason_Reason_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *FieldReason_Reason_Call) RunAndReturn(run func() string) *FieldReason_Reason_Call {
	_c.Call.Return(run)
	return _c
}
