// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockvalidate

import (
	mock "github.com/stretchr/testify/mock"
)

// NewValidator creates a new instance of Validator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Validator {
	mock := &Validator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

type Validator_Expecter struct {
	mock *mock.Mock
}

func (_m *Validator) EXPECT() *Validator_Expecter {
	return &Validator_Expecter{mock: &_m.Mock}
}

// ValidateAll provides a mock function for the type Validator
func (_mock *Validator) ValidateAll() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ValidateAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Validator_ValidateAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAll'
type Validator_ValidateAll_Call struct {
	*mock.Call
}

// ValidateAll is a helper method to define mock.On call
func (_e *Validator_Expecter) ValidateAll() *Validator_ValidateAll_Call {
	return &Validator_ValidateAll_Call{Call: _e.mock.On("ValidateAll")}
}

func (_c *Validator_ValidateAll_Call) Run(run func()) *Validator_ValidateAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Validator_ValidateAll_Call) Return(err error) *Validator_ValidateAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Validator_ValidateAll_Call) RunAndReturn(run func() error) *Validator_ValidateAll_Call {
	_c.Call.Return(run)
	return _c
}
