// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgrpcgateway

import (
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	mock "github.com/stretchr/testify/mock"
)

// NewHTTPServiceCustomizer creates a new instance of HTTPServiceCustomizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPServiceCustomizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPServiceCustomizer {
	mock := &HTTPServiceCustomizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HTTPServiceCustomizer is an autogenerated mock type for the HTTPServiceCustomizer type
type HTTPServiceCustomizer struct {
	mock.Mock
}

type HTTPServiceCustomizer_Expecter struct {
	mock *mock.Mock
}

func (_m *HTTPServiceCustomizer) EXPECT() *HTTPServiceCustomizer_Expecter {
	return &HTTPServiceCustomizer_Expecter{mock: &_m.Mock}
}

// GetMuxOptions provides a mock function for the type HTTPServiceCustomizer
func (_mock *HTTPServiceCustomizer) GetMuxOptions(defaultOptions []runtime.ServeMuxOption) []runtime.ServeMuxOption {
	ret := _mock.Called(defaultOptions)

	if len(ret) == 0 {
		panic("no return value specified for GetMuxOptions")
	}

	var r0 []runtime.ServeMuxOption
	if returnFunc, ok := ret.Get(0).(func([]runtime.ServeMuxOption) []runtime.ServeMuxOption); ok {
		r0 = returnFunc(defaultOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]runtime.ServeMuxOption)
		}
	}
	return r0
}

// HTTPServiceCustomizer_GetMuxOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMuxOptions'
type HTTPServiceCustomizer_GetMuxOptions_Call struct {
	*mock.Call
}

// GetMuxOptions is a helper method to define mock.On call
//   - defaultOptions []runtime.ServeMuxOption
func (_e *HTTPServiceCustomizer_Expecter) GetMuxOptions(defaultOptions interface{}) *HTTPServiceCustomizer_GetMuxOptions_Call {
	return &HTTPServiceCustomizer_GetMuxOptions_Call{Call: _e.mock.On("GetMuxOptions", defaultOptions)}
}

func (_c *HTTPServiceCustomizer_GetMuxOptions_Call) Run(run func(defaultOptions []runtime.ServeMuxOption)) *HTTPServiceCustomizer_GetMuxOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []runtime.ServeMuxOption
		if args[0] != nil {
			arg0 = args[0].([]runtime.ServeMuxOption)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HTTPServiceCustomizer_GetMuxOptions_Call) Return(serveMuxOptions []runtime.ServeMuxOption) *HTTPServiceCustomizer_GetMuxOptions_Call {
	_c.Call.Return(serveMuxOptions)
	return _c
}

func (_c *HTTPServiceCustomizer_GetMuxOptions_Call) RunAndReturn(run func(defaultOptions []runtime.ServeMuxOption) []runtime.ServeMuxOption) *HTTPServiceCustomizer_GetMuxOptions_Call {
	_c.Call.Return(run)
	return _c
}
