// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package errors

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetadataError creates a new instance of MockMetadataError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataError(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataError {
	mock := &MockMetadataError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetadataError is an autogenerated mock type for the MetadataError type
type MockMetadataError struct {
	mock.Mock
}

type MockMetadataError_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadataError) EXPECT() *MockMetadataError_Expecter {
	return &MockMetadataError_Expecter{mock: &_m.Mock}
}

// Metadata provides a mock function for the type MockMetadataError
func (_mock *MockMetadataError) Metadata() map[string]interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 map[string]interface{}
	if returnFunc, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}
	return r0
}

// MockMetadataError_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockMetadataError_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockMetadataError_Expecter) Metadata() *MockMetadataError_Metadata_Call {
	return &MockMetadataError_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockMetadataError_Metadata_Call) Run(run func()) *MockMetadataError_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetadataError_Metadata_Call) Return(stringToIfaceVal map[string]interface{}) *MockMetadataError_Metadata_Call {
	_c.Call.Return(stringToIfaceVal)
	return _c
}

func (_c *MockMetadataError_Metadata_Call) RunAndReturn(run func() map[string]interface{}) *MockMetadataError_Metadata_Call {
	_c.Call.Return(run)
	return _c
}
