// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package errors

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCodeError creates a new instance of MockCodeError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCodeError(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCodeError {
	mock := &MockCodeError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCodeError is an autogenerated mock type for the CodeError type
type MockCodeError struct {
	mock.Mock
}

type MockCodeError_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCodeError) EXPECT() *MockCodeError_Expecter {
	return &MockCodeError_Expecter{mock: &_m.Mock}
}

// Code provides a mock function for the type MockCodeError
func (_mock *MockCodeError) Code() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Code")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCodeError_Code_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Code'
type MockCodeError_Code_Call struct {
	*mock.Call
}

// Code is a helper method to define mock.On call
func (_e *MockCodeError_Expecter) Code() *MockCodeError_Code_Call {
	return &MockCodeError_Code_Call{Call: _e.mock.On("Code")}
}

func (_c *MockCodeError_Code_Call) Run(run func()) *MockCodeError_Code_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCodeError_Code_Call) Return(s string) *MockCodeError_Code_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCodeError_Code_Call) RunAndReturn(run func() string) *MockCodeError_Code_Call {
	_c.Call.Return(run)
	return _c
}
