// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockidgen

import (
	mock "github.com/stretchr/testify/mock"
)

// NewGenerator creates a new instance of Generator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Generator {
	mock := &Generator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Generator is an autogenerated mock type for the Generator type
type Generator struct {
	mock.Mock
}

type Generator_Expecter struct {
	mock *mock.Mock
}

func (_m *Generator) EXPECT() *Generator_Expecter {
	return &Generator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type Generator
func (_mock *Generator) Generate() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Generator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type Generator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *Generator_Expecter) Generate() *Generator_Generate_Call {
	return &Generator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *Generator_Generate_Call) Run(run func()) *Generator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Generator_Generate_Call) Return(s string) *Generator_Generate_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Generator_Generate_Call) RunAndReturn(run func() string) *Generator_Generate_Call {
	_c.Call.Return(run)
	return _c
}
